// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Rating struct {
	TrackID   int64  `json:"track_id"`
	Stars     int64  `json:"stars"`
	Opinion   string `json:"opinion"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncState struct {
	Key   string `json:"key"`
	Value int64  `json:"value"`
}

type Track struct {
	ID           int64  `json:"id"`
	SpotifyID    string `json:"spotify_id"`
	TrackName    string `json:"track_name"`
	AlbumName    string `json:"album_name"`
	Artists      string `json:"artists"`
	PlayCount    int64  `json:"play_count"`
	LastPlayedAt int64  `json:"last_played_at"`
	CreatedAt    int64  `json:"created_at"`
}
