// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getRatingByTrackID = `-- name: GetRatingByTrackID :one
SELECT track_id, stars, opinion, updated_at
FROM ratings
WHERE track_id = ?1
LIMIT 1
`

func (q *Queries) GetRatingByTrackID(ctx context.Context, trackID int64) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRatingByTrackID, trackID)
	var i Rating
	err := row.Scan(
		&i.TrackID,
		&i.Stars,
		&i.Opinion,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, spotify_id, track_name, album_name, artists, play_count, last_played_at, created_at
FROM tracks
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetTrackByID(ctx context.Context, id int64) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.TrackName,
		&i.AlbumName,
		&i.Artists,
		&i.PlayCount,
		&i.LastPlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTrackBySpotifyID = `-- name: GetTrackBySpotifyID :one
SELECT id, spotify_id, track_name, album_name, artists, play_count, last_played_at, created_at
FROM tracks
WHERE spotify_id = ?1
LIMIT 1
`

func (q *Queries) GetTrackBySpotifyID(ctx context.Context, spotifyID string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackBySpotifyID, spotifyID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.TrackName,
		&i.AlbumName,
		&i.Artists,
		&i.PlayCount,
		&i.LastPlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentTracks = `-- name: ListRecentTracks :many
SELECT id, spotify_id, track_name, album_name, artists, play_count, last_played_at, created_at
FROM tracks
ORDER BY last_played_at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListRecentTracks(ctx context.Context, limit int64) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTracks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.TrackName,
			&i.AlbumName,
			&i.Artists,
			&i.PlayCount,
			&i.LastPlayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPlayedTracks = `-- name: ListTopPlayedTracks :many
SELECT id, spotify_id, track_name, album_name, artists, play_count, last_played_at, created_at
FROM tracks
ORDER BY play_count DESC, last_played_at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListTopPlayedTracks(ctx context.Context, limit int64) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTopPlayedTracks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.TrackName,
			&i.AlbumName,
			&i.Artists,
			&i.PlayCount,
			&i.LastPlayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnratedTracks = `-- name: ListUnratedTracks :many
SELECT t.id, t.spotify_id, t.track_name, t.album_name, t.artists, t.play_count, t.last_played_at, t.created_at
FROM tracks AS t
LEFT JOIN ratings AS r ON r.track_id = t.id
WHERE r.track_id IS NULL
ORDER BY t.last_played_at DESC, t.id DESC
LIMIT ?1
`

func (q *Queries) ListUnratedTracks(ctx context.Context, limit int64) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listUnratedTracks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.TrackName,
			&i.AlbumName,
			&i.Artists,
			&i.PlayCount,
			&i.LastPlayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (
    track_id,
    stars,
    opinion,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
ON CONFLICT (track_id) DO UPDATE SET
    stars = excluded.stars,
    opinion = excluded.opinion,
    updated_at = excluded.updated_at
RETURNING track_id, stars, opinion, updated_at
`

type UpsertRatingParams struct {
	TrackID   int64  `json:"track_id"`
	Stars     int64  `json:"stars"`
	Opinion   string `json:"opinion"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, upsertRating,
		arg.TrackID,
		arg.Stars,
		arg.Opinion,
		arg.UpdatedAt,
	)
	var i Rating
	err := row.Scan(
		&i.TrackID,
		&i.Stars,
		&i.Opinion,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrack = `-- name: UpsertTrack :one
INSERT INTO tracks (
    spotify_id,
    track_name,
    album_name,
    artists,
    last_played_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
ON CONFLICT (spotify_id) DO UPDATE SET
    track_name = excluded.track_name,
    album_name = excluded.album_name,
    artists = excluded.artists,
    play_count = tracks.play_count + 1,
    last_played_at = excluded.last_played_at
RETURNING id, spotify_id, track_name, album_name, artists, play_count, last_played_at, created_at
`

type UpsertTrackParams struct {
	SpotifyID    string `json:"spotify_id"`
	TrackName    string `json:"track_name"`
	AlbumName    string `json:"album_name"`
	Artists      string `json:"artists"`
	LastPlayedAt int64  `json:"last_played_at"`
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, upsertTrack,
		arg.SpotifyID,
		arg.TrackName,
		arg.AlbumName,
		arg.Artists,
		arg.LastPlayedAt,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.TrackName,
		&i.AlbumName,
		&i.Artists,
		&i.PlayCount,
		&i.LastPlayedAt,
		&i.CreatedAt,
	)
	return i, err
}
