// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetRatingByTrackID(ctx context.Context, trackID int64) (Rating, error)
	GetTrackByID(ctx context.Context, id int64) (Track, error)
	GetTrackBySpotifyID(ctx context.Context, spotifyID string) (Track, error)
	ListAllRatings(ctx context.Context) ([]Rating, error)
	ListAllTracks(ctx context.Context) ([]Track, error)
	ListRecentTracks(ctx context.Context, limit int64) ([]Track, error)
	ListTopPlayedTracks(ctx context.Context, limit int64) ([]Track, error)
	ListUnratedTracks(ctx context.Context, limit int64) ([]Track, error)
	UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error)
	UpsertTrack(ctx context.Context, arg UpsertTrackParams) (Track, error)
}

var _ Querier = (*Queries)(nil)
